- hosts: localhost
  become: true
  tasks:
    - name: Install basic utilities
      apt: name={{item}}
      with_items:
        - curl
        - htop
        - ffmpeg
        - lm-sensors
        - htop
        - shellcheck
        - vim

